"""Canonical figure API names.

This module exposes the non-"Smart" names for the interactive plotting stack
while preserving full compatibility with the legacy ``SmartFigure`` module.
"""

from .SmartFigure import (
    FIGURE_DEFAULT,
    InfoPanelManager,
    OneShotOutput,
    ParameterManager,
    SmartFigure as Figure,
    SmartFigure,
    SmartFigureLayout as FigureLayout,
    SmartPlot as Plot,
    SmartPlot,
    add_info_component,
    current_figure,
    get_info_output,
    get_sampling_points,
    get_title,
    get_x_range,
    get_y_range,
    parameter,
    parameters,
    params,
    plot,
    plot_style_options,
    plots,
    render,
    set_sampling_points,
    set_title,
    set_x_range,
    set_y_range,
)

__all__ = [
    "FIGURE_DEFAULT",
    "OneShotOutput",
    "FigureLayout",
    "ParameterManager",
    "InfoPanelManager",
    "Plot",
    "Figure",
    "SmartFigure",
    "SmartPlot",
    "current_figure",
    "set_title",
    "get_title",
    "render",
    "get_info_output",
    "add_info_component",
    "set_x_range",
    "get_x_range",
    "set_y_range",
    "get_y_range",
    "set_sampling_points",
    "get_sampling_points",
    "plot_style_options",
    "parameter",
    "parameters",
    "params",
    "plots",
    "plot",
]
