"""Compatibility function exports for module-level figure helpers."""

from ..SmartFigure import (
    add_info_component,
    get_info_output,
    get_sampling_points,
    get_title,
    get_x_range,
    get_y_range,
    parameter,
    parameters,
    params,
    plot,
    plot_style_options,
    plots,
    render,
    set_sampling_points,
    set_title,
    set_x_range,
    set_y_range,
)

__all__ = [
    "set_title",
    "get_title",
    "render",
    "get_info_output",
    "add_info_component",
    "set_x_range",
    "get_x_range",
    "set_y_range",
    "get_y_range",
    "set_sampling_points",
    "get_sampling_points",
    "plot_style_options",
    "parameter",
    "parameters",
    "params",
    "plots",
    "plot",
]
